export const Strings = {
  enterName: 'Enter Name',
  login: 'Login',
  profile: 'Profile',
  home: 'Home',
  save: 'Save',
  create: 'Create',
  createExpense: 'Create Expense',
  editExpense: 'Edit Expense',
  title: 'Title',
  amount: 'Amount',
  date: 'Date',
  totalItems: 'Total Expenses Items',
  totalExpenses: 'Total Expenses:',
  signOut: 'Sign out',
  filters: 'Filters',
  filter: 'Filter',
  clear: 'Clear',
};
